package com.example.semantic;

public enum ErrorType {
    NO_COMPONENTS_FOUND,
    BAD_PROPERTY_DECLARATION,
    BAD_COMPONENT_DECLARATION,
    BAD_ATTRIBUTE_DECLARATION,
    PROPERTY_TYPE_NOT_EXISTS,
    CONSTANT_VALUE_NOT_EXISTS,
    ATTRIBUTE_NOT_EXISTS,
    VALUE_INVALID
}
