package com.example.semantic;

public enum ErrorType {
    NO_COMPONENTS,
    BAD_PROPERTY_DECLARATION,
    BAD_COMPONENT_DECLARATION,
    BAD_ATTRIBUTE_DECLARATION,
    BAD_TYPE_DECLARATION,
    BAD_CONSTANT_VALUE_DECLARATION,
    BAD_VALUE_DECLARATION,
    COMPONENT_NOT_FOUND
}
